### PR TITLE
tutorial example pipeline

### PR DESCRIPTION
**Pull request by zehsilva**

### CODE REVIEW

**Review by oddaspa — APPROVED** [review]
Disclaimer first. I had to create a pipeline and checkout the branch tutorial_project, therefore not following the normal flow described in the tutorial.

Import error when trying to open a node in edit mode. Works fine after opening src folder then trying again.
Screenshot 2021-11-30 at 13 22 51

Still getting plotly error. (Dismiss the other error, I hadn't updated the item id)
Screenshot 2021-11-30 at 13 30 15

When running all nodes simultaneously there is an output Error. Running the nodes sequentially works as expected.
Screenshot 2021-11-30 at 13 36 12

Other than that it works. I think the code can be cleaner, but that is for another day. Since we don't have that much time I think we can merge it, but the issues should be resolved in a later PR.

**Comment by zehsilva** [comment]
The error you encountered could be a result of how you need to import the project in order to test. Do the error continue if after checking out the branch you restarted the pipeline?

**Comment by zehsilva** [comment]
Screenshot 2021-11-30 at 13 36 12

This error sometimes appears in general, not only in this project when running the session interactively multiple times, usually, it resolves after restarting the memory server or restarting the session.

Yes, it would be nice to have a cleaner code and should be done at some point.

**Comment by oddaspa** [comment]
> The error you encountered could be a result of how you need to import the project in order to test. Do the error continue if after checking out the branch you restarted the pipeline?

Are your referring to the Plotly Warning? If so, no the warning persists.

**Comment by zehsilva** [comment]
> Are your referring to the Plotly Warning? If so, no the warning persists.

No, the others. Yes, plotly error is because of prophet, it won't go away (I have looked into it in the past, it can be filtered out by redirecting sys.stderr). The error right after of NoneType and the error about OutputNotFound is this memory server error it seems.

**Review by AlexiaArtemis — APPROVED** [review]
Perfect ✨🙌

**Comment by oddaspa** [comment]
> No, the others. 

Alright, the error for opening a node goes away, after trying to open once. The OutputNotFoundError persists even after restarting. (only when running all nodes simultaneously)

**Pull request merged**
