### PR TITLE
Template project with Clarify nodes and forecast pipeline

### PR DESCRIPTION
**Pull request by zehsilva**
Template project that can be imported to Orchest. 

Includes:
- Read / write nodes to Clarify using PyClarify
- Read and forecast nodes using Merlion

### CODE REVIEW

**Comment by oddaspa** [comment]
How would you like me to review this?

**Comment by zehsilva** [comment]
One possibility would be to test if you can import this as a new project on a clean Orchest instance and then try to run the pipeline (by adding your credential files to the `src` folder in the Orchest project). So mostly if it is functional, the pipeline works and is intuitive. The documentation / tutorial is still in the works, but there should be more explanation about the inner workings. 

About the code inside each node, I am unsure about the level of exposure we want to create there, but you could take a look and review also if you can understand it mostly at a functional level. If you have any suggestions on how to improve the code I am open to it, as well as the choice of naming the variables when passing between nodes (the naming will be also explained and discussed in the tutorial, I am half way through it). Thanks!

**Comment by zehsilva** [comment]
Ah, also test building the environment (because the project includes the `setup.sh` file with the dependencies and build). The workflow is 
- Import project in Orchest (using the Github link, although I am unsure if it works well with branches, in my own setup I was using another public copy on my own GitHub to make it easy to import)
- Check if the pipeline appear correctly 
- Check if the build goes well
- Some feedback about the code / naming of variables to pass through the pipeline

**Comment by oddaspa** [comment]
> * Import project in Orchest (using the Github link, although I am unsure if it works well with branches, in my own setup I was using another public copy on my own GitHub to make it easy to import)

This might only be the workflow because the files are still in dev:
- Create a import project with Github URL
- Create a pipeline, and add an empty node
- Open file explorer
- Delete all created files
- Checkout dev
- Go to pipelines and open "Read, Forecast and Write to Clarify"
- Build the environment (some of the build failed)

Screenshot 2021-11-18 at 09 50 53

- The "Forecast with lag and future" failed, which is weird because the node doesn't use Plotly

Screenshot 2021-11-18 at 09 54 28

- Running the steps individually instead of all at the same time works, but then I get another error

Screenshot 2021-11-18 at 10 02 43

- Fixing missing `item_id` in the `pipeline_data` method 
- Finish running the steps 


This is the pipeline that appears when checking out dev.

Screenshot 2021-11-18 at 10 21 44

Why is there a seemingly useless "Read Item" node?

**Comment by zehsilva** [comment]
Thanks, I will try to import again the project from zero and see why these errors appear. Yes, some of these errors are a bit weird, but I will check carefully if there is some import left unused that I didn't see at first.

> Why is there a seemingly useless "Read Item" node?

The plan there is to have it in the pipeline to explain in the tutorial that there is a node for reading that the user can use further for other tasks. Maybe in order to make it less useless, I could make a node for plotting a graph of the data read?

**Comment by oddaspa** [comment]
> Maybe in order to make it less seamless, I could make a node for plotting a graph of the data read?

That depends on your vision of the tutorial 😄 You could have it as an input to the forecasting node, and split the work of reading and forecasting, and that way keep the flexibility of the nodes. I just read your comments on this pull request so I assume I would know why the "read node" is there if I followed your tutorial.  

Let me know when you have updated and I will review again :)

**Comment by zehsilva** [comment]
>  You could have it as an input to the forecasting node, and split the work of reading and forecasting, ...

Yeah, I thought about that option, but one issue here is the memory server of the pipeline (it has a memory server with a configurable maximum amount of data that can be passed via pipeline arguments). So to increase the number of signals and range of time that can be processed at once I chose to have the read + prediction in only one step.

**Comment by oddaspa** [comment]
> Yeah, I thought about that option, but one issue here is the memory server of the pipeline (it has a memory server with a configurable maximum amount of data that can be passed via pipeline arguments). So to increase the number of signals and range of time that can be processed at once I chose to have the read + prediction in only one step.

Okay, then it has a good motivation. I think you should mention that in the tutorial and keep it as is 👍

**Pull request closed without merging**
